# Bioinformatics Project | Computational Drug Discovery | Part 1 

In this project, we will be building a real-life **Drug Discovery** model, i.e., to predict molecular activity from chemical descriptors. Particularly, we will be building a machine learning model using the ChEMBL bioactivity data.

In **Part 1**, we will be performing Data Collection and Pre-Processing from the ChEMBL Database.

---

## **ChEMBL Database**

The [*ChEMBL Database*](https://www.ebi.ac.uk/chembl/) is a database that contains curated bioactivity data of more than 2 million compounds. It is compiled from more than 76,000 documents, 1.2 million assays and the data spans 13,000 targets and 1,800 cells and 33,000 indications.
[Data as of 30<sup>th</sup> May, 2026;].

## **Importing libraries**

In [ ]:
import pandas as pd
from chembl_webresource_client.new_client import new_client

## **Search for Target protein**

### **Target search for Acetylcholinesterase (Target protein for Alzymers)**

In [2]:
# Target search for acetylcholinesterase
target = new_client.target
target_query = target.search("acetylcholinesterase")
targets = pd.DataFrame.from_dict(target_query)
targets

,cross_references,organism,pref_name,score,species_group_flag,target_chembl_id,target_components,target_type,tax_id
0,[],Drosophila melanogaster,Acetylcholinesterase,18.0,False,CHEMBL2242744,"[{'accession': 'P07140', 'component_descriptio...",SINGLE PROTEIN,7227
1,[],Homo sapiens,Acetylcholinesterase,16.0,False,CHEMBL220,"[{'accession': 'P22303', 'component_descriptio...",SINGLE PROTEIN,9606
2,[],Torpedo californica,Acetylcholinesterase,16.0,False,CHEMBL4780,"[{'accession': 'P04058', 'component_descriptio...",SINGLE PROTEIN,7787
3,[],Mus musculus,Acetylcholinesterase,16.0,False,CHEMBL3198,"[{'accession': 'P21836', 'component_descriptio...",SINGLE PROTEIN,10090
4,[],Rattus norvegicus,Acetylcholinesterase,16.0,False,CHEMBL3199,"[{'accession': 'P37136', 'component_descriptio...",SINGLE PROTEIN,10116
5,[],Electrophorus electricus,Acetylcholinesterase,16.0,False,CHEMBL4078,"[{'accession': 'O42275', 'component_descriptio...",SINGLE PROTEIN,8005
6,[],Bos taurus,Acetylcholinesterase,16.0,False,CHEMBL4768,"[{'accession': 'P23795', 'component_descriptio...",SINGLE PROTEIN,9913
7,[],Anopheles gambiae,Acetylcholinesterase,16.0,False,CHEMBL2046266,"[{'accession': 'Q869C3', 'component_descriptio...",SINGLE PROTEIN,7165
8,[],Bemisia tabaci,AChE2,16.0,False,CHEMBL2366409,"[{'accession': 'B3SST5', 'component_descriptio...",SINGLE PROTEIN,7038
9,[],Leptinotarsa decemlineata,Acetylcholinesterase,16.0,False,CHEMBL2366490,"[{'accession': 'Q27677', 'component_descriptio...",SINGLE PROTEIN,7539
10,[],Nephotettix cincticeps,Ace-orthologous acetylcholinesterase,16.0,False,CHEMBL2366514,"[{'accession': 'Q9NJH6', 'component_descriptio...",SINGLE PROTEIN,94400
11,[],Gallus gallus,Acetylcholinesterase,16.0,False,CHEMBL3227914,"[{'accession': 'P36196', 'component_descriptio...",SINGLE PROTEIN,9031
12,[],Danio rerio,Acetylcholinesterase,16.0,False,CHEMBL3308995,"[{'accession': 'Q9DDE3', 'component_descriptio...",SINGLE PROTEIN,7955
13,[],Aedes aegypti,Acetylcholinesterase,16.0,False,CHEMBL4295607,"[{'accession': 'Q6A2E2', 'component_descriptio...",SINGLE PROTEIN,7159
14,[],Homo sapiens,Protein CutA,16.0,False,CHEMBL6067022,"[{'accession': 'O60888', 'component_descriptio...",SINGLE PROTEIN,9606
15,[],Musca domestica,Acetylcholinesterase,15.0,False,CHEMBL5752,"[{'accession': 'Q95P20', 'component_descriptio...",SINGLE PROTEIN,7370
16,[],Plutella xylostella,Acetylcholinesterase,15.0,False,CHEMBL2242729,"[{'accession': 'Q8MZM0', 'component_descriptio...",SINGLE PROTEIN,51655
17,[],Musca domestica,Acetylcholinesterase,15.0,False,CHEMBL2242743,"[{'accession': 'Q7YWJ9', 'component_descriptio...",SINGLE PROTEIN,7370
18,[],Pediculus humanus capitis,Acetylcholinesterase,15.0,False,CHEMBL2362988,"[{'accession': 'A2PZ98', 'component_descriptio...",SINGLE PROTEIN,121226
19,[],Spodoptera litura,Acetylcholinesterase,15.0,False,CHEMBL2366422,"[{'accession': 'C5IU80', 'component_descriptio...",SINGLE PROTEIN,69820
20,[],Laodelphax striatella,Acetylcholinesterase,15.0,False,CHEMBL2366446,"[{'accession': 'K4JQ36', 'component_descriptio...",SINGLE PROTEIN,195883
21,[],Schizaphis graminum,Acetylcholinesterase,15.0,False,CHEMBL2366511,"[{'accession': 'Q9BMJ1', 'component_descriptio...",SINGLE PROTEIN,13262
22,[],Homo sapiens,Cholinesterases; ACHE & BCHE,14.0,False,CHEMBL2095233,"[{'accession': 'P06276', 'component_descriptio...",SELECTIVITY GROUP,9606
23,[],Rattus norvegicus,Acetylcholinesterase and butyrylcholinesterase...,14.0,False,CHEMBL2111475,"[{'accession': 'P37136', 'component_descriptio...",SELECTIVITY GROUP,10116
24,[],Caenorhabditis elegans,Acetylcholinesterase 1,14.0,False,CHEMBL3341583,"[{'accession': 'P38433', 'component_descriptio...",SINGLE PROTEIN,6239
25,[],Equus caballus,Butyrylcholinesterase,11.0,False,CHEMBL5077,"[{'accession': 'Q9N1N9', 'component_descriptio...",SINGLE PROTEIN,9796
26,[],Equus caballus,Cholinesterase,11.0,False,CHEMBL5763,"[{'accession': 'P81908', 'component_descriptio...",SINGLE PROTEIN,9796
27,[],Canis lupus familiaris,Cholinesterase,11.0,False,CHEMBL4630814,"[{'accession': 'P32750', 'component_descriptio...",SINGLE PROTEIN,9615
28,[],Mus musculus,Cholinesterase,10.0,False,CHEMBL2528,"[{'accession': 'Q03311', 'component_descriptio...",SINGLE PROTEIN,10090
29,[],Rattus norvegicus,Butyrylcholinesterase,10.0,False,CHEMBL3403,"[{'accession': 'Q9JKC1', 'component_descriptio...",SINGLE PROTEIN,10116
30,[],Homo sapiens,Cholinesterase,5.0,False,CHEMBL1914,"[{'accession': 'P06276', 'component_descriptio...",SINGLE PROTEIN,9606

The above table shows all targets whose name is related to acetylcholinesterase.

For more info see `Knowledge_Base.md`

### Select and retrieve the bioactivity data for Human Acetylcholinesterase

In [3]:
selected_target = targets['target_chembl_id'][1]
selected_target

'CHEMBL220'

In [4]:
activity = new_client.activity
res = activity.filter(target_chembl_id= selected_target).filter(standard_type= "IC50")

In [10]:
activities = list(res)
df = pd.DataFrame(activities)
df

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,33969,[],CHEMBL643384,Inhibitory concentration against acetylcholine...,B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,None,None,IC50,uM,UO_0000065,None,0.75
1,None,None,37563,[],CHEMBL643384,Inhibitory concentration against acetylcholine...,B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,None,None,IC50,uM,UO_0000065,None,0.1
2,None,None,37565,[],CHEMBL643384,Inhibitory concentration against acetylcholine...,B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,None,None,IC50,uM,UO_0000065,None,50.0
3,None,None,38902,[],CHEMBL643384,Inhibitory concentration against acetylcholine...,B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,None,None,IC50,uM,UO_0000065,None,0.3
4,None,None,41170,[],CHEMBL643384,Inhibitory concentration against acetylcholine...,B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,None,None,IC50,uM,UO_0000065,None,0.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10074,"{'action_type': 'INHIBITOR', 'description': 'N...",None,29307984,[],CHEMBL6183009,Inhibition of AChE (unknown origin),B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,None,None,IC50,uM,UO_0000065,None,0.4
10075,"{'action_type': 'INHIBITOR', 'description': 'N...",None,29307985,[],CHEMBL6183009,Inhibition of AChE (unknown origin),B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,None,None,IC50,uM,UO_0000065,None,2.16
10076,"{'action_type': 'INHIBITOR', 'description': 'N...",None,29309041,[],CHEMBL6183244,Inhibition of AChE (unknown origin),B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,None,None,IC50,nM,UO_0000065,None,11.1
10077,"{'action_type': 'INHIBITOR', 'description': 'N...",None,29309042,[],CHEMBL6183244,Inhibition of AChE (unknown origin),B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,None,None,IC50,uM,UO_0000065,None,0.052
10078,"{'action_type': 'INHIBITOR', 'description': 'N...",None,29309043,[],CHEMBL6183244,Inhibition of AChE (unknown origin),B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,None,None,IC50,nM,UO_0000065,None,2.61

In [12]:
df.columns

Index(['action_type', 'activity_comment', 'activity_id', 'activity_properties',
       'assay_chembl_id', 'assay_description', 'assay_type',
       'assay_variant_accession', 'assay_variant_mutation', 'bao_endpoint',
       'bao_format', 'bao_label', 'canonical_smiles', 'data_validity_comment',
       'data_validity_description', 'document_chembl_id', 'document_journal',
       'document_year', 'ligand_efficiency', 'modality', 'molecule_chembl_id',
       'molecule_pref_name', 'parent_molecule_chembl_id', 'pchembl_value',
       'potential_duplicate', 'qudt_units', 'record_id', 'relation', 'src_id',
       'standard_flag', 'standard_relation', 'standard_text_value',
       'standard_type', 'standard_units', 'standard_upper_value',
       'standard_value', 'target_chembl_id', 'target_organism',
       'target_pref_name', 'target_tax_id', 'text_value', 'toid', 'type',
       'units', 'uo_units', 'upper_value', 'value'],
      dtype='object')

In [ ]:
df['canonical_smiles'].isna().sum()

39

In [15]:
df['standard_value'].isna().sum()

1286

We don't want molecules that have missing values in `canonical_smiles` or `standard_value`

In [20]:
df2 = df[df.canonical_smiles.notna()]
df2 = df2[df2.standard_value.notna()]
df2

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,33969,[],CHEMBL643384,Inhibitory concentration against acetylcholine...,B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,None,None,IC50,uM,UO_0000065,None,0.75
1,None,None,37563,[],CHEMBL643384,Inhibitory concentration against acetylcholine...,B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,None,None,IC50,uM,UO_0000065,None,0.1
2,None,None,37565,[],CHEMBL643384,Inhibitory concentration against acetylcholine...,B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,None,None,IC50,uM,UO_0000065,None,50.0
3,None,None,38902,[],CHEMBL643384,Inhibitory concentration against acetylcholine...,B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,None,None,IC50,uM,UO_0000065,None,0.3
4,None,None,41170,[],CHEMBL643384,Inhibitory concentration against acetylcholine...,B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,None,None,IC50,uM,UO_0000065,None,0.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10074,"{'action_type': 'INHIBITOR', 'description': 'N...",None,29307984,[],CHEMBL6183009,Inhibition of AChE (unknown origin),B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,None,None,IC50,uM,UO_0000065,None,0.4
10075,"{'action_type': 'INHIBITOR', 'description': 'N...",None,29307985,[],CHEMBL6183009,Inhibition of AChE (unknown origin),B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,None,None,IC50,uM,UO_0000065,None,2.16
10076,"{'action_type': 'INHIBITOR', 'description': 'N...",None,29309041,[],CHEMBL6183244,Inhibition of AChE (unknown origin),B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,None,None,IC50,nM,UO_0000065,None,11.1
10077,"{'action_type': 'INHIBITOR', 'description': 'N...",None,29309042,[],CHEMBL6183244,Inhibition of AChE (unknown origin),B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,None,None,IC50,uM,UO_0000065,None,0.052
10078,"{'action_type': 'INHIBITOR', 'description': 'N...",None,29309043,[],CHEMBL6183244,Inhibition of AChE (unknown origin),B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,None,None,IC50,nM,UO_0000065,None,2.61

In [21]:
print(df2['canonical_smiles'].isna().sum())
print(df2['standard_value'].isna().sum())

0
0

In [24]:
len(df2['canonical_smiles'].unique())

7175

We only want molecules with unique chemical descriptors

In [38]:
df3 = df2.drop_duplicates(['canonical_smiles'])
df3

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,33969,[],CHEMBL643384,Inhibitory concentration against acetylcholine...,B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,None,None,IC50,uM,UO_0000065,None,0.75
1,None,None,37563,[],CHEMBL643384,Inhibitory concentration against acetylcholine...,B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,None,None,IC50,uM,UO_0000065,None,0.1
2,None,None,37565,[],CHEMBL643384,Inhibitory concentration against acetylcholine...,B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,None,None,IC50,uM,UO_0000065,None,50.0
3,None,None,38902,[],CHEMBL643384,Inhibitory concentration against acetylcholine...,B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,None,None,IC50,uM,UO_0000065,None,0.3
4,None,None,41170,[],CHEMBL643384,Inhibitory concentration against acetylcholine...,B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,None,None,IC50,uM,UO_0000065,None,0.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10073,"{'action_type': 'INHIBITOR', 'description': 'N...",None,29307981,[],CHEMBL6183007,Inhibition of AChE (unknown origin) using acet...,B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,None,None,IC50,nM,UO_0000065,None,0.48
10074,"{'action_type': 'INHIBITOR', 'description': 'N...",None,29307984,[],CHEMBL6183009,Inhibition of AChE (unknown origin),B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,None,None,IC50,uM,UO_0000065,None,0.4
10076,"{'action_type': 'INHIBITOR', 'description': 'N...",None,29309041,[],CHEMBL6183244,Inhibition of AChE (unknown origin),B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,None,None,IC50,nM,UO_0000065,None,11.1
10077,"{'action_type': 'INHIBITOR', 'description': 'N...",None,29309042,[],CHEMBL6183244,Inhibition of AChE (unknown origin),B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,None,None,IC50,uM,UO_0000065,None,0.052
10078,"{'action_type': 'INHIBITOR', 'description': 'N...",None,29309043,[],CHEMBL6183244,Inhibition of AChE (unknown origin),B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,None,None,IC50,nM,UO_0000065,None,2.61

We don't need so many columns for our purpose. We only need `molecule_chembl_id`, `canonical_smiles` & `standard_value`

In [39]:
selection = ['molecule_chembl_id', 'canonical_smiles', 'standard_value']
df4 = df3[selection]
df4

,molecule_chembl_id,canonical_smiles,standard_value
0,CHEMBL133897,CCOc1nn(-c2cccc(OCc3ccccc3)c2)c(=O)o1,750.0
1,CHEMBL336398,O=C(N1CCCCC1)n1nc(-c2ccc(Cl)cc2)nc1SCC1CC1,100.0
2,CHEMBL131588,CN(C(=O)n1nc(-c2ccc(Cl)cc2)nc1SCC(F)(F)F)c1ccccc1,50000.0
3,CHEMBL130628,O=C(N1CCCCC1)n1nc(-c2ccc(Cl)cc2)nc1SCC(F)(F)F,300.0
4,CHEMBL130478,CSc1nc(-c2ccc(OC(F)(F)F)cc2)nn1C(=O)N(C)C,800.0
...,...,...,...
10073,CHEMBL6190210,FC(F)(F)c1cccc(-c2cc(-c3cccs3)n(-c3ccc(Br)cc3)...,0.48
10074,CHEMBL6192902,O=C(NNC(=S)Nc1ccccc1[N+](=O)[O-])c1sccc1Cl,400.0
10076,CHEMBL6191782,Cc1cc(=O)[nH]c2c1C(=O)C(NCNc1c3c(nc4ccccc14)CC...,11.1
10077,CHEMBL6190113,O=C(NCCCNc1c2c(nc3ccccc13)CCC2)c1cnc(Cl)c(Cl)c1,52.0
10078,CHEMBL6188323,COc1cc2c(cc1OC)CC(CN1CCN(CCCNc3c4c(nc5cc(Cl)cc...,2.61

Let's categorise the molecules based on `standard_values` as active (<1000 nM), inactive (>1000 nM) and intermediate (in between)

In [41]:
df4.standard_value.info()

<class 'pandas.core.series.Series'>
Index: 7175 entries, 0 to 10078
Series name: standard_value
Non-Null Count  Dtype
--------------  -----
7175 non-null   object
dtypes: object(1)
memory usage: 112.1+ KB

In [42]:
df4['standard_value'] = df4['standard_value'].astype("float64")

<ipython-input-42-fe96df8ca460>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df4['standard_value'] = df4['standard_value'].astype("float64")

In [44]:
import numpy as np
conditions = [
    df4['standard_value'] < 1000,
    (df4['standard_value'] >= 1000) &  (df4['standard_value'] <= 10000),
    df4['standard_value'] > 10000
]
choices = ['active', 'intermediate', 'inactive']

df4['class'] = np.select(conditions, choices)

<ipython-input-44-bb7dff301adc>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df4['class'] = np.select(conditions, choices)

In [70]:
df4

,molecule_chembl_id,canonical_smiles,standard_value,class
0,CHEMBL133897,CCOc1nn(-c2cccc(OCc3ccccc3)c2)c(=O)o1,750.00,active
1,CHEMBL336398,O=C(N1CCCCC1)n1nc(-c2ccc(Cl)cc2)nc1SCC1CC1,100.00,active
2,CHEMBL131588,CN(C(=O)n1nc(-c2ccc(Cl)cc2)nc1SCC(F)(F)F)c1ccccc1,50000.00,inactive
3,CHEMBL130628,O=C(N1CCCCC1)n1nc(-c2ccc(Cl)cc2)nc1SCC(F)(F)F,300.00,active
4,CHEMBL130478,CSc1nc(-c2ccc(OC(F)(F)F)cc2)nn1C(=O)N(C)C,800.00,active
...,...,...,...,...
10073,CHEMBL6190210,FC(F)(F)c1cccc(-c2cc(-c3cccs3)n(-c3ccc(Br)cc3)...,0.48,active
10074,CHEMBL6192902,O=C(NNC(=S)Nc1ccccc1[N+](=O)[O-])c1sccc1Cl,400.00,active
10076,CHEMBL6191782,Cc1cc(=O)[nH]c2c1C(=O)C(NCNc1c3c(nc4ccccc14)CC...,11.10,active
10077,CHEMBL6190113,O=C(NCCCNc1c2c(nc3ccccc13)CCC2)c1cnc(Cl)c(Cl)c1,52.00,active
10078,CHEMBL6188323,COc1cc2c(cc1OC)CC(CN1CCN(CCCNc3c4c(nc5cc(Cl)cc...,2.61,active

In [87]:
df4.reset_index(drop= True, inplace= True)
df4

,molecule_chembl_id,canonical_smiles,standard_value,class
0,CHEMBL133897,CCOc1nn(-c2cccc(OCc3ccccc3)c2)c(=O)o1,750.00,active
1,CHEMBL336398,O=C(N1CCCCC1)n1nc(-c2ccc(Cl)cc2)nc1SCC1CC1,100.00,active
2,CHEMBL131588,CN(C(=O)n1nc(-c2ccc(Cl)cc2)nc1SCC(F)(F)F)c1ccccc1,50000.00,inactive
3,CHEMBL130628,O=C(N1CCCCC1)n1nc(-c2ccc(Cl)cc2)nc1SCC(F)(F)F,300.00,active
4,CHEMBL130478,CSc1nc(-c2ccc(OC(F)(F)F)cc2)nn1C(=O)N(C)C,800.00,active
...,...,...,...,...
7170,CHEMBL6190210,FC(F)(F)c1cccc(-c2cc(-c3cccs3)n(-c3ccc(Br)cc3)...,0.48,active
7171,CHEMBL6192902,O=C(NNC(=S)Nc1ccccc1[N+](=O)[O-])c1sccc1Cl,400.00,active
7172,CHEMBL6191782,Cc1cc(=O)[nH]c2c1C(=O)C(NCNc1c3c(nc4ccccc14)CC...,11.10,active
7173,CHEMBL6190113,O=C(NCCCNc1c2c(nc3ccccc13)CCC2)c1cnc(Cl)c(Cl)c1,52.00,active
7174,CHEMBL6188323,COc1cc2c(cc1OC)CC(CN1CCN(CCCNc3c4c(nc5cc(Cl)cc...,2.61,active

A dot in a SMILES string indicates disconnected molecular fragments. We need to remove salts and multi-component molecules before descriptor calculation.

In [95]:
df4[df4['canonical_smiles'].str.contains(r"\.")]

,molecule_chembl_id,canonical_smiles,standard_value,class
34,CHEMBL54126,CN(C)C(=O)Oc1cccc([N+](C)(C)C)c1.[Br-],22.0,active
35,CHEMBL297316,C[N+](C)(C)CCS/C(=N\O)C(=O)c1ccc(F)cc1.[Cl-],1000000.0,inactive
38,CHEMBL296429,Cc1ccc(C(=O)/C(=N/O)SCC[N+](C)(C)C)cc1.[Cl-],1000000.0,inactive
41,CHEMBL544022,CCN(CC)CCS/C(=N\O)C(=O)c1ccc(Cl)cc1.Cl,520000.0,inactive
44,CHEMBL45118,CC[N+](C)(CC)CCS/C(=N\O)C(=O)c1ccc(OC)cc1.[Cl-],1000000.0,inactive
...,...,...,...,...
6961,CHEMBL6102746,C[n+]1cc(F)ccc1/C=N/O.[I-],277300.0,inactive
6962,CHEMBL6145299,C[n+]1cc(Cl)ccc1/C=N/O.[I-],132600.0,inactive
6963,CHEMBL6133183,C[n+]1cc(Br)ccc1/C=N/O.[I-],58500.0,inactive
6974,CHEMBL6149735,COc1cc(N)c(F)cc1C(=O)CCC1CCN(CC2CCCCC2)CC1.O=C...,29.0,active
7147,CHEMBL6170062,Cl.[2H]c1ccc2nc3c(c(N)c2c1)CCCC3,198.0,active

**NOTE:** In .str.contains(), the pattern is treated as a regular expression (regex) by default. And in regex "." means "match any single character", not a literal dot.

In [96]:
df_no_smiles = df4.drop('canonical_smiles', axis= 1)

In [97]:
smiles = []

for i in df4.canonical_smiles.tolist():
    val = str(i).split('.')
    val_longest = max(val, key= len)
    smiles.append(val_longest)

can_smiles = pd.Series(smiles, name= "canonical_smiles")

In [99]:
df_cleaned = pd.concat([df_no_smiles, can_smiles], axis= 1)[['molecule_chembl_id', 'canonical_smiles', 'standard_value', 'class']]

In [100]:
df_cleaned

,molecule_chembl_id,canonical_smiles,standard_value,class
0,CHEMBL133897,CCOc1nn(-c2cccc(OCc3ccccc3)c2)c(=O)o1,750.00,active
1,CHEMBL336398,O=C(N1CCCCC1)n1nc(-c2ccc(Cl)cc2)nc1SCC1CC1,100.00,active
2,CHEMBL131588,CN(C(=O)n1nc(-c2ccc(Cl)cc2)nc1SCC(F)(F)F)c1ccccc1,50000.00,inactive
3,CHEMBL130628,O=C(N1CCCCC1)n1nc(-c2ccc(Cl)cc2)nc1SCC(F)(F)F,300.00,active
4,CHEMBL130478,CSc1nc(-c2ccc(OC(F)(F)F)cc2)nn1C(=O)N(C)C,800.00,active
...,...,...,...,...
7170,CHEMBL6190210,FC(F)(F)c1cccc(-c2cc(-c3cccs3)n(-c3ccc(Br)cc3)...,0.48,active
7171,CHEMBL6192902,O=C(NNC(=S)Nc1ccccc1[N+](=O)[O-])c1sccc1Cl,400.00,active
7172,CHEMBL6191782,Cc1cc(=O)[nH]c2c1C(=O)C(NCNc1c3c(nc4ccccc14)CC...,11.10,active
7173,CHEMBL6190113,O=C(NCCCNc1c2c(nc3ccccc13)CCC2)c1cnc(Cl)c(Cl)c1,52.00,active
7174,CHEMBL6188323,COc1cc2c(cc1OC)CC(CN1CCN(CCCNc3c4c(nc5cc(Cl)cc...,2.61,active

Now save this dataframe into csv

In [ ]:
df_cleaned.to_csv('Data/acetylcholinesterase_01_bioactivity_data_curated.csv', index=False)